# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./Defines.h \
    ./QDefines.h \
    ./SWForm.h \
    ./TObject.h \
    ./DBC/DBCFileLoader.h \
    ./DBC/DBCfmt.h \
    ./DBC/DBCStore.h \
    ./DBC/DBCStores.h \
    ./DBC/DBCStructure.h \
    ./Includes/Dynamic/FactoryHolder.h \
    ./Includes/Dynamic/ObjectRegistry.h \
    ./Includes/GameSystem/Grid.h \
    ./Includes/GameSystem/GridLoader.h \
    ./Includes/GameSystem/GridReference.h \
    ./Includes/GameSystem/GridRefManager.h \
    ./Includes/GameSystem/NGrid.h \
    ./Includes/GameSystem/TypeContainer.h \
    ./Includes/GameSystem/TypeContainerFunctions.h \
    ./Includes/GameSystem/TypeContainerFunctionsPtr.h \
    ./Includes/GameSystem/TypeContainerVisitor.h \
    ./Includes/Platform/CompilerDefs.h \
    ./Includes/Platform/Define.h \
    ./Includes/Policies/CreationPolicy.h \
    ./Includes/Policies/ObjectLifeTime.h \
    ./Includes/Policies/Singleton.h \
    ./Includes/Policies/SingletonImp.h \
    ./Includes/Policies/ThreadingModel.h \
    ./Includes/Utilities/ByteConverter.h \
    ./Includes/Utilities/Callback.h \
    ./Includes/Utilities/EventProcessor.h \
    ./Includes/Utilities/LinkedList.h \
    ./Includes/Utilities/TypeList.h \
    ./Includes/Utilities/UnorderedMapSet.h \
    ./Includes/Utilities/LinkedReference/Reference.h \
    ./Includes/Utilities/LinkedReference/RefManager.h \
    SWObject.h \
    SWSearch.h \
    AboutForm.h \
    SWEvent.h \
    SWDefines.h
SOURCES += ./Main.cpp \
    ./SWForm.cpp \
    ./TObject.cpp \
    ./DBC/DBCFileLoader.cpp \
    ./DBC/DBCStores.cpp \
    ./Includes/Policies/ObjectLifeTime.cpp \
    ./Includes/Utilities/EventProcessor.cpp \
    SWObject.cpp \
    SWSearch.cpp \
    AboutForm.cpp \
    SWEvent.cpp \
    SWDefines.cpp
FORMS += ./AboutFormUI.ui \
    ./SWFormUI.ui
RESOURCES += ./SpellWork.qrc
